### ISSUE TITLE
如何判断哪个资源被汉化会导致功能不可用呢？

### ISSUE THREAD

**Issue by yihuishou** [ewen0930/IntelliJ-IDEA-Chinese#2]
求经验~

**Comment by ewen0930** [comment]
没什么经验，根据使用情况和网友反馈判断，再排错；
比如：https://github.com/ewen0930/WebStorm-Chinese/issues/6
https://github.com/ewen0930/PyCharm-Chinese/issues/6

**Comment by yihuishou** [comment]
== 这几个汉化包通用吗？

**Comment by ewen0930** [comment]
主体是一样的，各自有些差别
