### ISSUE TITLE
请问有计划更新到 2018.2 吗？

### ISSUE THREAD

**Issue by l-we** [ewen0930/IntelliJ-IDEA-Chinese#5]
请问有计划更新到 2018.2 吗？

**Comment by ewen0930** [comment]
已更新
https://github.com/ewen0930/IntelliJ-IDEA-Chinese/releases/tag/0.8.2-beta-v2018.2

**Comment by l-we** [comment]
thx

**Comment by wezhyn** [comment]
目前 2018.2.2可以用吗？？？我将它导入来我/opt/idea/lib中，重启没有用
